resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: angular
  - path: image-patch.yaml
    target:
      kind: Deployment
      name: angular

commonLabels:
  app: dev-angular
namespace: dev
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=dev
    name: angular
