resources:
- ../../base
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: angular
commonLabels:
  app: dev-angular
namespace: dev
configMapGenerator:
- behavior: merge
  literals:
  - ENV=dev
  name: angular
images:
- name: angular-k8s
  newName: /angular-k8s
  newTag: 729fe8ddb45fda35b914ea97852cda3331f7c293
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
