resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: angular-k8s
  newName: 5h4k4r/angular-k8s
  newTag: dev
