resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: angular

commonLabels:
  app: prod-angular
namespace: prod
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=prod
    name: angular
