resources:
- ../../base
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: angular
commonLabels:
  app: prod-angular
namespace: prod
replicas:
- count: 2
  name: angular
images:
- name: 5h4k4r/angular-k8s
  newName: 5h4k4r/angular-k8s
  newTag: d82358154ac6eeda458e46221977bcfade53cb90
- name: angular
  newTag: 6b654da03c0e
namePrefix: prod-
configMapGenerator:
- behavior: merge
  literals:
  - ENV=prod
  name: angular
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
