resources:
- ../../base
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: angular

commonLabels:
  app: staging-angular
namespace: staging
configMapGenerator:
- behavior: merge
  literals:
  - ENV=staging
  name: angular
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 5h4k4r/angular-k8s
  newName: 5h4k4r/angular-k8s
  newTag: 345cb8d8f9795da18ca676536352514afdfe5a97
