name: Publish Docker image

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - ".vscode/**"
concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: push-to-docker

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd kubernetes/overlays/dev
          kustomize edit set image angular-k8s=$DOCKER_USERNAME/angular-k8s:$GITHUB_SHA
          cat kustomization.yaml

      # - name: Commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit -am "Bump docker tag"

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

      # - name: Notify argocd
      #   uses: clowdhaus/argo-cd-action/@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     version: 2.4.11
      #     command: app create angular-dev --insecure --repo https://github.com/5h4k4r/angular-app --path kubernetes/overlays/dev --dest-namespace dev --dest-server https://kubernetes.default.svc --kustomize-image 5h4k4r/angular-k8s:$${{ github.ref_name }} --server argocd.shakar.tech

      # - uses: actions/checkout@v2
      # - name: Sync ArgoCD Application
      #   uses: omegion/argocd-actions@v1
      #   with:
      #     address: "dev.shakar.com"
      #     token: ${{ secrets.ARGOCD_TOKEN }}
      #     action: sync
      #     appName: "angular-dev"
